export const galleryData = [
  // Team Vibes
  {
    id: "team-1",
    category: "team",
    src: "/static/gallery/team-1.jpg",
    alt: "Team members collaborating",
    title: "Brainstorm Session",
    caption: "When the ideas start flowing and the coffee kicks in ☕",
    height: 300,
  },
  {
    id: "team-2",
    category: "team",
    src: "/static/gallery/team-2.jpg",
    alt: "Team celebration",
    title: "Milestone Celebration",
    caption: "10,000 followers party! 🎉",
    height: 350,
  },
  {
    id: "team-3",
    category: "team",
    src: "/static/gallery/team-3.jpg",
    alt: "Team building activity",
    title: "Team Building",
    caption: "Building trust and friendships one game at a time",
    height: 280,
    hasMascot: true,
  },

  // Creative Campaigns
  {
    id: "creative-1",
    category: "creative",
    src: "/static/gallery/creative-1.jpg",
    alt: "Campaign photoshoot",
    title: "Freshman Guide Shoot",
    caption: "Behind the lens of our most viral campaign",
    height: 320,
  },
  {
    id: "creative-2",
    category: "creative",
    src: "/static/gallery/creative-2.jpg",
    alt: "Design mockups",
    title: "Design Process",
    caption: "From sketches to final designs",
    height: 280,
  },
  {
    id: "creative-3",
    category: "creative",
    src: "/static/gallery/creative-3.jpg",
    alt: "Content creation",
    title: "Content Magic",
    caption: "Creating content that resonates with college students",
    height: 300,
  },

  // Work Hard, Play Hard
  {
    id: "work-1",
    category: "work",
    src: "/static/gallery/work-1.jpg",
    alt: "Late night work session",
    title: "Deadline Crunch",
    caption: "3 AM and still going strong 💪",
    height: 300,
  },
  {
    id: "work-2",
    category: "work",
    src: "/static/gallery/work-2.jpg",
    alt: "Office party",
    title: "Friday Celebrations",
    caption: "Work hard, party harder",
    height: 350,
  },
  {
    id: "work-3",
    category: "work",
    src: "/static/gallery/work-3.jpg",
    alt: "Team outing",
    title: "Team Retreat",
    caption: "Annual team bonding in the mountains",
    height: 280,
  },

  // Behind-The-Scenes
  {
    id: "bts-1",
    category: "bts",
    src: "/static/gallery/bts-1.jpg",
    alt: "Video shoot setup",
    title: "Lights, Camera, Action!",
    caption: "Setting up for our YouTube series",
    height: 320,
  },
  {
    id: "bts-2",
    category: "bts",
    src: "/static/gallery/bts-2.jpg",
    alt: "Interview preparation",
    title: "Interview Prep",
    caption: "Getting ready to interview college celebrities",
    height: 300,
    hasMascot: true,
  },
  {
    id: "bts-3",
    category: "bts",
    src: "/static/gallery/bts-3.jpg",
    alt: "Content planning",
    title: "Content Calendar",
    caption: "Planning our content strategy for the semester",
    height: 280,
  },

  // Office Antics
  {
    id: "office-1",
    category: "office",
    src: "/static/gallery/office-1.jpg",
    alt: "Office prank",
    title: "Prank Wars",
    caption: "When the marketing team strikes back",
    height: 300,
  },
  {
    id: "office-2",
    category: "office",
    src: "/static/gallery/office-2.jpg",
    alt: "Desk decoration",
    title: "Desk Makeover",
    caption: "Caught snacking mid-call 😅",
    height: 320,
  },
  {
    id: "office-3",
    category: "office",
    src: "/static/gallery/office-3.jpg",
    alt: "Office pets",
    title: "Office Mascots",
    caption: "Our unofficial team members",
    height: 280,
  },

  // Meme the Moment
  {
    id: "meme-1",
    category: "meme",
    src: "/static/gallery/meme-1.jpg",
    memeSrc: "/static/gallery/meme-1-overlay.jpg",
    alt: "Meeting meme",
    title: "Meeting Reality",
    caption: "How meetings actually go...",
    height: 300,
  },
  {
    id: "meme-2",
    category: "meme",
    src: "/static/gallery/meme-2.jpg",
    memeSrc: "/static/gallery/meme-2-overlay.jpg",
    alt: "Deadline meme",
    title: "Deadline Approaching",
    caption: "T-minus 1 hour to submission",
    height: 320,
  },
  {
    id: "meme-3",
    category: "meme",
    src: "/static/gallery/meme-3.jpg",
    memeSrc: "/static/gallery/meme-3-overlay.jpg",
    alt: "Coffee meme",
    title: "Coffee Dependency",
    caption: "The fuel that powers CollegeTips",
    height: 280,
    hasMascot: true,
  },

  // Game (Find the Mascot)
  {
    id: "game-1",
    category: "game",
    src: "/static/gallery/game-1.jpg",
    alt: "Office scene with hidden mascot",
    title: "Spot the Fox",
    caption: "Our mascot is hiding somewhere in this image!",
    height: 320,
  },
  {
    id: "game-2",
    category: "game",
    src: "/static/gallery/game-2.jpg",
    alt: "Team photo with hidden mascot",
    title: "Where's Foxy?",
    caption: "Can you find our mascot?",
    height: 300,
  },
  {
    id: "game-3",
    category: "game",
    src: "/static/gallery/game-3.jpg",
    alt: "Event photo with hidden mascot",
    title: "Mascot Hunt",
    caption: "Our mascot snuck into this event photo!",
    height: 280,
  },
]
